name: Notify Discord on Push

on:
  push:
    branches:
      - '**'

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send push notification to Discord
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1277683113287356436/wqfLNQDK_tMg1PSk2e0V0EZ-ic4JuwQqLLK7Y4Ti-elOzQ3GNkh1WHXEZhlWKkW2A7cn
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"Push event in repository: *${{ github.repository }}* on branch: *${{ github.ref_name }}*\nCommit message: *${{ github.event.head_commit.message }}*\nPushed by: *${{ github.actor }}*\"}" \
               $DISCORD_WEBHOOK
